import { useEffect, useState } from 'react';
import Head from "next/head";
import styles from "../styles/Home.module.css";

const startingCards = [
  { name:"bunny",
    open:false,
  },
  { name:"dog",
    open:false,
  },
  { name:"cat",
    open:false,
  },
  { name:"dog",
    open:false,
  },
  { name:"cat",
    open:false,
  },
  { name:"bunny",
    open:false,
  },
];


// const setStuff = (newStuff) => {
//   stuff = newStuff;
// }

// const useState2 = (defaultValue) => {
//   const stuff = defaultValue;

//   return [
//     stuff,
//     setStuff
//   ]
// }

export default function Home() {
const [cards, setCards] = useState(startingCards);


function handleCounter () {
  setCounter(counter + 1);
}

function flipCard(index) { 
  setCards(prev => {
    const newCards = [...prev];
    newCards[index].open = true;
    return newCards;
  })
};

useEffect(() => {
  const selectedCards = cards.filter(card => card.open === true).length;
  
  if (selectedCards === 2) {
    setTimeout(() => {
      setCards(prev => {
        const newCards = [...prev];
        newCards.map(card => card.open = false);
        return newCards;
      })
    }, 1000);
  }
}, [cards])

  return (
    <div className={styles.container}>
      <Head>
        <title>memory game</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>memory game</h1>

        <p className={styles.description}>
          punteggio 0  
        </p>
        <div className={styles.grid}>
        {cards.map((card, index) => (
            <div className={styles.card} key={index} onClick={()=>{flipCard(index)}} >{card.open ? card.name : index+1}</div>
        ))}
        </div>

        {/* al click si apre la card */}
        {/* se le due carte sono uguali si lasciano aperte */}
        {/* se le due carte sono diverse si chiudono */}
      </main>
    </div>
  );
}
